# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "06ed9fe65a2d63a7db2fdce227c977a8"
name = "October Pincode"
application_url = "https://pincode-plugin.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = ["app/uninstalled"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = ["app/scopes_update"]

[access_scopes]
scopes = "write_app_proxy"

[auth]
redirect_urls = [ "https://pincode-plugin.vercel.app/auth/callback" ]

[app_proxy]
# Storefront /apps/pincode/check → app /apps/pincode/check
url = "/apps/pincode"
prefix = "apps"
subpath = "pincode"
